https://{default}/:
  type: upstream
  upstream: app:http
  cache:
    enabled: true
    cookies:
    - /^SS?ESS/
https://www.{default}/:
  type: redirect
  to: https://{default}/
http://www.{default}/:
  type: redirect
  redirects:
    expires: -1s
    paths: {}
  to: https://{default}/
