https://www.{default}/:
  type: redirect
  to: https://{default}/
http://www.{default}/:
  type: redirect
  redirects:
    expires: -1s
    paths: {}
  to: https://{default}/
http://{default}/:
  type: redirect
  redirects:
    expires: -1s
    paths: {}
  to: https://{default}/
